In [1]:
import numpy as np

In [2]:
arry = np.array([[1,2,3,4],[1,3,4,5]])

In [3]:
arry

array([[1, 2, 3, 4],
       [1, 3, 4, 5]])

In [4]:
l  = [1,2,3,4,5,6]

In [5]:
l

[1, 2, 3, 4, 5, 6]

In [6]:
l1 = [1,3,4,5,6,7,8,'naveen',56.8]

In [7]:
l1

[1, 3, 4, 5, 6, 7, 8, 'naveen', 56.8]

In [8]:
np.array(l1)

array(['1', '3', '4', '5', '6', '7', '8', 'naveen', '56.8'], dtype='<U32')

In [9]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.array([[[1,2,3,4],[5,3,2,4],[3,4,53,5]]])

array([[[ 1,  2,  3,  4],
        [ 5,  3,  2,  4],
        [ 3,  4, 53,  5]]])

In [11]:
a1 = np.array(l1)

In [12]:
a2 = np.array([[1,2,3],[4,5,6]])

In [13]:
a3 = np.array([[[1,2,3,4],[5,3,2,4],[3,4,53,5]]])

In [14]:
a1

array(['1', '3', '4', '5', '6', '7', '8', 'naveen', '56.8'], dtype='<U32')

In [15]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a3

array([[[ 1,  2,  3,  4],
        [ 5,  3,  2,  4],
        [ 3,  4, 53,  5]]])

# ndim means dimenstiond

In [17]:

a1.ndim

1

In [18]:

a2.ndim

2

In [19]:
a3.ndim

3

In [20]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

# size

In [21]:
a1.size

9

In [22]:
a2.size

6

In [23]:
a3.size

12

In [24]:
a1.shape

(9,)

In [25]:
a2.shape

(2, 3)

In [26]:
a3.shape

(1, 3, 4)

In [27]:
a3

array([[[ 1,  2,  3,  4],
        [ 5,  3,  2,  4],
        [ 3,  4, 53,  5]]])

# random.randint, random.rand, random.randn
### random.randint :-means it genetate the random int from 2 to 5
### random.rand :-
### random.randn :-

In [28]:
np.random.randint(2,5)

3

In [29]:
np.random.randint(2,50,(2,3,4))

array([[[ 7, 43, 45, 17],
        [29, 26, 47, 47],
        [ 5, 26, 17,  9]],

       [[10, 21, 22, 18],
        [42, 30, 39,  7],
        [28, 19, 20, 42]]])

In [30]:
np.random.rand(2,3)

array([[0.30684231, 0.31981115, 0.29089327],
       [0.93399324, 0.46280068, 0.56538886]])

In [31]:
np.random.randn(4,3)

array([[ 0.03367514, -0.76651118,  1.24128073],
       [ 1.22580374, -2.05083628,  0.14312809],
       [-0.80366831, -0.64154823, -0.20962986],
       [ 0.27973657,  0.63104106,  1.06581855]])

In [32]:
a4 = np.random.rand(4,4) # here value is 4x4 is 16
                         # here 4*4 means not into we read as 4 cross 4 

In [33]:
a4

array([[0.71423623, 0.21809696, 0.23485649, 0.20492234],
       [0.90037296, 0.61617399, 0.55748325, 0.06517839],
       [0.64939651, 0.66056868, 0.38876816, 0.03069276],
       [0.44874993, 0.73520074, 0.03472156, 0.72160906]])

In [34]:
a4.reshape(3,4) # here the values are 3x3 (3 cross 4) 12
                # here 3x4 is not equal to 4x3 because 
                # 3x4 means 3 rows and 4 columns
                # where as 4x3 means 4 rows and 3 columns

ValueError: cannot reshape array of size 16 into shape (3,4)

In [35]:
a4.reshape(2,8) 

array([[0.71423623, 0.21809696, 0.23485649, 0.20492234, 0.90037296,
        0.61617399, 0.55748325, 0.06517839],
       [0.64939651, 0.66056868, 0.38876816, 0.03069276, 0.44874993,
        0.73520074, 0.03472156, 0.72160906]])

In [36]:
a4.reshape(8,2) 

array([[0.71423623, 0.21809696],
       [0.23485649, 0.20492234],
       [0.90037296, 0.61617399],
       [0.55748325, 0.06517839],
       [0.64939651, 0.66056868],
       [0.38876816, 0.03069276],
       [0.44874993, 0.73520074],
       [0.03472156, 0.72160906]])

In [37]:
a4.reshape(16,1) 

array([[0.71423623],
       [0.21809696],
       [0.23485649],
       [0.20492234],
       [0.90037296],
       [0.61617399],
       [0.55748325],
       [0.06517839],
       [0.64939651],
       [0.66056868],
       [0.38876816],
       [0.03069276],
       [0.44874993],
       [0.73520074],
       [0.03472156],
       [0.72160906]])

In [38]:
a4.reshape(2,-1) # 2X-1 means that automatically the numpy can detect what is the factorial or what is the shape and what is the number
                 # Then automatically the numpy will give you the shape or array
# we cannot just leave writing (2,) and leave in this case it will give an error
# we can write any negative number not only -1, we can give any number
# we can give any number of numbers no problem
# but we are using a4, so a4 total value is [a4 = np.random.rand(4,4)] 4x4 = 16
# it should not excide the factorial of 16 we can give 16X1 or 8X2....etc and negative values as well like  (2,2,-4), (2,1,2,1,-4)

array([[0.71423623, 0.21809696, 0.23485649, 0.20492234, 0.90037296,
        0.61617399, 0.55748325, 0.06517839],
       [0.64939651, 0.66056868, 0.38876816, 0.03069276, 0.44874993,
        0.73520074, 0.03472156, 0.72160906]])

In [39]:
a4.reshape(2,2,-4)

array([[[0.71423623, 0.21809696, 0.23485649, 0.20492234],
        [0.90037296, 0.61617399, 0.55748325, 0.06517839]],

       [[0.64939651, 0.66056868, 0.38876816, 0.03069276],
        [0.44874993, 0.73520074, 0.03472156, 0.72160906]]])

In [40]:
a4.reshape(2,1,2,1,-4)

array([[[[[0.71423623, 0.21809696, 0.23485649, 0.20492234]],

         [[0.90037296, 0.61617399, 0.55748325, 0.06517839]]]],



       [[[[0.64939651, 0.66056868, 0.38876816, 0.03069276]],

         [[0.44874993, 0.73520074, 0.03472156, 0.72160906]]]]])

In [41]:
# There are more than 2000+ functions are avaliable in numpy 
# but mostly we use 10 to 20 functions in numpy and randint,rand,randn,reshape...etc are some of the most  used functions

In [42]:
a1

array(['1', '3', '4', '5', '6', '7', '8', 'naveen', '56.8'], dtype='<U32')

In [43]:
a1[0]

'1'

In [44]:
a1[2:6] # list slicing operations

array(['4', '5', '6', '7'], dtype='<U32')

In [45]:
a1[::-1]

array(['56.8', 'naveen', '8', '7', '6', '5', '4', '3', '1'], dtype='<U32')

In [46]:
a1[2:6:2]

array(['4', '6'], dtype='<U32')

In [47]:
a1[::-1]

array(['56.8', 'naveen', '8', '7', '6', '5', '4', '3', '1'], dtype='<U32')

In [48]:
a3

array([[[ 1,  2,  3,  4],
        [ 5,  3,  2,  4],
        [ 3,  4, 53,  5]]])

In [49]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
a2[0]

array([1, 2, 3])

In [51]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
a2[:,1:] # which means that ==> [:,1:] :, means that start from first and give me the 1 column and ==>: means that go till end

array([[2, 3],
       [5, 6]])

In [53]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [54]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [55]:
np.random.randint(2,8,(6,5))

array([[7, 3, 5, 6, 2],
       [4, 5, 7, 5, 7],
       [2, 2, 5, 5, 3],
       [4, 4, 5, 7, 4],
       [5, 6, 7, 5, 4],
       [3, 2, 2, 6, 4]])

In [60]:
a5 = np.random.randint(2,80,(6,5))

In [61]:
a5

array([[65, 39, 13, 64, 30],
       [22, 60, 63,  6, 34],
       [11, 19, 62, 48, 78],
       [ 5, 14, 43, 33, 18],
       [52, 18, 18, 23, 28],
       [32, 20, 10, 20, 73]])

In [62]:
a5

array([[65, 39, 13, 64, 30],
       [22, 60, 63,  6, 34],
       [11, 19, 62, 48, 78],
       [ 5, 14, 43, 33, 18],
       [52, 18, 18, 23, 28],
       [32, 20, 10, 20, 73]])

In [63]:
a5[a5>40]

array([65, 64, 60, 63, 62, 48, 78, 43, 52, 73])

In [64]:
a5

array([[65, 39, 13, 64, 30],
       [22, 60, 63,  6, 34],
       [11, 19, 62, 48, 78],
       [ 5, 14, 43, 33, 18],
       [52, 18, 18, 23, 28],
       [32, 20, 10, 20, 73]])

In [65]:
a5[0,1] = 100

In [66]:
a5

array([[ 65, 100,  13,  64,  30],
       [ 22,  60,  63,   6,  34],
       [ 11,  19,  62,  48,  78],
       [  5,  14,  43,  33,  18],
       [ 52,  18,  18,  23,  28],
       [ 32,  20,  10,  20,  73]])

In [73]:
a6 = np.random.randint(0,3,(3,3))

In [74]:
a6

array([[2, 2, 1],
       [2, 2, 1],
       [2, 0, 1]])

In [75]:
a7 = np.random.randint(0,3,(3,3))

In [76]:
a7

array([[1, 1, 1],
       [1, 1, 2],
       [0, 2, 1]])

In [77]:
a6*a7 # this is know as element wise multiplication

array([[2, 2, 1],
       [2, 2, 2],
       [0, 0, 1]])

 # @ is used to perform matrix maltipication operations in numpy  

In [79]:
a6@a7

array([[4, 6, 7],
       [4, 6, 7],
       [2, 4, 3]])

In [80]:
a6+100

array([[102, 102, 101],
       [102, 102, 101],
       [102, 100, 101]])

In [83]:
a6*2

array([[4, 4, 2],
       [4, 4, 2],
       [4, 0, 2]])

In [84]:
a6/0

C:\Users\Naveen\AppData\Local\Temp\ipykernel_2412\1058679823.py:1: RuntimeWarning: divide by zero encountered in divide
  a6/0
C:\Users\Naveen\AppData\Local\Temp\ipykernel_2412\1058679823.py:1: RuntimeWarning: invalid value encountered in divide
  a6/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, nan, inf]])

In [85]:
a6**3 # power operations power of 3

array([[8, 8, 1],
       [8, 8, 1],
       [8, 0, 1]], dtype=int32)

In [87]:
# zero operations
a8 = np.zeros((4,4))

In [88]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [90]:
a9 = np.ones((4,5))

In [91]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [94]:
# here it is performing row wise addidion operations
a9 + np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [95]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [97]:
a9+np.array([1,2,3,5,6])

array([[2., 3., 4., 6., 7.],
       [2., 3., 4., 6., 7.],
       [2., 3., 4., 6., 7.],
       [2., 3., 4., 6., 7.]])

In [98]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [99]:
# this entire opertion are known as Broadcast Operations
a9+np.array([1,2,3,5]) # here we are getting error because we are preforming one less row operations

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [100]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [101]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [102]:
np.array([1,4,3,4])

array([1, 4, 3, 4])

In [113]:
# T stants for transpose operation 
# transpose means rotating matrix


np.array([1,4,3,4]).T
# we will get an error because it is one dimenstion array
# so that the reason we are getting  an error 
# now use two brakets like [[1,2,3,4]].T This will work 
# you can see on the next line below, bottom line, line no 106


array([1, 4, 3, 4])

In [106]:
np.array([[1,4,3,4]]).T

array([[1],
       [4],
       [3],
       [4]])

In [107]:
np.array([[1,4,3,4]]).T+a9

array([[2., 2., 2., 2., 2.],
       [5., 5., 5., 5., 5.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [108]:
a5

array([[ 65, 100,  13,  64,  30],
       [ 22,  60,  63,   6,  34],
       [ 11,  19,  62,  48,  78],
       [  5,  14,  43,  33,  18],
       [ 52,  18,  18,  23,  28],
       [ 32,  20,  10,  20,  73]])

In [109]:
np.sqrt(a5)

array([[ 8.06225775, 10.        ,  3.60555128,  8.        ,  5.47722558],
       [ 4.69041576,  7.74596669,  7.93725393,  2.44948974,  5.83095189],
       [ 3.31662479,  4.35889894,  7.87400787,  6.92820323,  8.83176087],
       [ 2.23606798,  3.74165739,  6.55743852,  5.74456265,  4.24264069],
       [ 7.21110255,  4.24264069,  4.24264069,  4.79583152,  5.29150262],
       [ 5.65685425,  4.47213595,  3.16227766,  4.47213595,  8.54400375]])

In [111]:
np.exp(a5)

array([[1.69488924e+28, 2.68811714e+43, 4.42413392e+05, 6.23514908e+27,
        1.06864746e+13],
       [3.58491285e+09, 1.14200739e+26, 2.29378316e+27, 4.03428793e+02,
        5.83461743e+14],
       [5.98741417e+04, 1.78482301e+08, 8.43835667e+26, 7.01673591e+20,
        7.49841700e+33],
       [1.48413159e+02, 1.20260428e+06, 4.72783947e+18, 2.14643580e+14,
        6.56599691e+07],
       [3.83100800e+22, 6.56599691e+07, 6.56599691e+07, 9.74480345e+09,
        1.44625706e+12],
       [7.89629602e+13, 4.85165195e+08, 2.20264658e+04, 4.85165195e+08,
        5.05239363e+31]])

In [112]:
np.log10(a5)

array([[1.81291336, 2.        , 1.11394335, 1.80617997, 1.47712125],
       [1.34242268, 1.77815125, 1.79934055, 0.77815125, 1.53147892],
       [1.04139269, 1.2787536 , 1.79239169, 1.68124124, 1.8920946 ],
       [0.69897   , 1.14612804, 1.63346846, 1.51851394, 1.25527251],
       [1.71600334, 1.25527251, 1.25527251, 1.36172784, 1.44715803],
       [1.50514998, 1.30103   , 1.        , 1.30103   , 1.86332286]])

In [115]:
# floating point is not allowed in range function
range(0,10,2.5)

TypeError: 'float' object cannot be interpreted as an integer

In [116]:
# in numpy there is arange functions

In [117]:
np.arange(1.5,10.5,2.3)

array([1.5, 3.8, 6.1, 8.4])

In [118]:
# IN a straight line here are will be infinity numbers 
# linespace helps us to locate the points in between 2 and 3
# That the reason we are getting the points and we also gave num = 50 so the points will be upto 50

np.linspace(2,3,num= 50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [120]:
np.linspace(2,3,num= 50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [124]:
# retstep means tells that the at whih level of point  is spacing or located or 
# it tells us how much point space it took to another point
# here it took 0.02040816326530612 to take a next point location
np.linspace(2,3,num= 50,retstep = True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [125]:
np.logspace(2,4, num = 4, base = 10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [126]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])