In [3]:
import numpy as np

In [4]:
np.array([2,3,42,1,3,3,4])

array([ 2,  3, 42,  1,  3,  3,  4])

In [5]:
type(np.array([2,3,4,2,4,2,4,2,4]))

numpy.ndarray

In [10]:
np.array([[1,3,4],[4,56,3]])

array([[ 1,  3,  4],
       [ 4, 56,  3]])

In [11]:
np.array([[1,2,3,4,],[5,4,6,7]])

array([[1, 2, 3, 4],
       [5, 4, 6, 7]])

In [12]:
l = [[1,2,3,4,],[5,4,6,7]]

In [13]:
l[0]

[1, 2, 3, 4]

In [14]:
l[0][0]

1

In [15]:
a = np.array([3,4,5,6],ndmin= 5)

In [16]:
a

array([[[[[3, 4, 5, 6]]]]])

In [19]:
a1 = np.array([3,4,5,6],ndmin= 3)

In [20]:
a1

array([[[3, 4, 5, 6]]])

In [21]:
arr = np.array([[1,2,4], [2,3,4], [4,6,5]])

In [22]:
arr

array([[1, 2, 4],
       [2, 3, 4],
       [4, 6, 5]])

In [23]:
arr.ndim

2

In [24]:
# randint is it genetate random integer
np.random.randint(1,10,(4,4))

array([[6, 2, 9, 3],
       [3, 6, 5, 2],
       [4, 5, 4, 8],
       [5, 5, 8, 5]])

In [29]:
np.random.randint(1,10,(4,4,2))


array([[[6, 5],
        [5, 2],
        [2, 5],
        [9, 9]],

       [[2, 9],
        [1, 6],
        [4, 8],
        [8, 5]],

       [[8, 1],
        [2, 2],
        [4, 6],
        [7, 5]],

       [[2, 2],
        [8, 3],
        [2, 9],
        [6, 1]]])